/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type PullQuote = {
  _type: "pullQuote";
  quote?: string;
  attribution?: string;
};

export type MediaImage = {
  _type: "mediaImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  credit?: string;
};

export type LocalizedSlug = {
  _type: "localizedSlug";
  pl?: string;
  en?: string;
};

export type LocalizedText = {
  _type: "localizedText";
  pl?: string;
  en?: string;
};

export type LocalizedString = {
  _type: "localizedString";
  pl?: string;
  en?: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: ArticleReference;
  language?: string;
};

export type PlaceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "place";
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type HotelReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "hotel";
};

export type ExperienceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "experience";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  format?: "story" | "profile" | "guide" | "recipe";
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              target?:
                | PlaceReference
                | PersonReference
                | ProductReference
                | HotelReference
                | ExperienceReference;
              _type: "entityLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & MediaImage)
    | ({
        _key: string;
      } & PullQuote)
  >;
  featured?: boolean;
  heroImage?: MediaImage;
  gallery?: Array<
    {
      _key: string;
    } & MediaImage
  >;
  category?: CategoryReference;
  location?: Array<
    {
      _key: string;
    } & PlaceReference
  >;
  people?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  experiences?: Array<
    {
      _key: string;
    } & ExperienceReference
  >;
  hotel?: Array<
    {
      _key: string;
    } & HotelReference
  >;
  related?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
  author?: AuthorReference;
  publishedAt?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  bio?: LocalizedText;
  photo?: MediaImage;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?: "food" | "craft" | "stay" | "experiences" | "history" | "people";
  name?: LocalizedString;
  slugs?: LocalizedSlug;
  intro?: LocalizedText;
  cover?: MediaImage;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
  kind?: "tasting" | "workshop" | "outdoor" | "sea" | "festival" | "culture";
  place?: PlaceReference;
  people?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  description?: LocalizedText;
  image?: MediaImage;
  durationMinutes?: number;
  seasons?: Array<string>;
  priceNote?: LocalizedString;
  bookingUrl?: string;
};

export type Hotel = {
  _id: string;
  _type: "hotel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  type?: "hotel" | "boutique" | "agriturismo" | "bnb" | "villa";
  place?: PlaceReference;
  summary?: LocalizedText;
  image?: MediaImage;
  gallery?: Array<
    {
      _key: string;
    } & MediaImage
  >;
  priceRange?:
    | "\u20AC"
    | "\u20AC\u20AC"
    | "\u20AC\u20AC\u20AC"
    | "\u20AC\u20AC\u20AC\u20AC";
  websiteUrl?: string;
  bookingUrl?: string;
  isAffiliate?: boolean;
  isSponsored?: boolean;
  coordinates?: Geopoint;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocalizedString;
  slug?: Slug;
  kind?: "food" | "drink" | "craft";
  protectedStatus?: "none" | "DOP" | "IGP" | "STG" | "DOC" | "DOCG" | "PAT";
  description?: LocalizedText;
  image?: MediaImage;
  origin?: Array<
    {
      _key: string;
    } & PlaceReference
  >;
  makers?: Array<
    {
      _key: string;
    } & PersonReference
  >;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: LocalizedString;
  bio?: LocalizedText;
  portrait?: MediaImage;
  location?: Array<
    {
      _key: string;
    } & PlaceReference
  >;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type Place = {
  _id: string;
  _type: "place";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocalizedString;
  slug?: Slug;
  kind?: "region" | "city" | "village" | "coast" | "landmark";
  parent?: PlaceReference;
  mapId?: string;
  summary?: LocalizedText;
  cover?: MediaImage;
  coordinates?: Geopoint;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | PullQuote
  | MediaImage
  | LocalizedSlug
  | LocalizedText
  | LocalizedString
  | TranslationMetadata
  | InternationalizedArrayReference
  | ArticleReference
  | InternationalizedArrayReferenceValue
  | PlaceReference
  | PersonReference
  | ProductReference
  | HotelReference
  | ExperienceReference
  | CategoryReference
  | AuthorReference
  | Article
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Slug
  | Category
  | Experience
  | Hotel
  | Geopoint
  | Product
  | Person
  | Place
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;
